#!/usr/bin/env python3#
#krl 10-13-22

fav_dict = {'book' : 'Catcher in the Rye' , 'song' : 'Michael Jackson-Thriller' , 'tree' : 'poplar'}
print (fav_dict)

fav_thing = 'book'
print(fav_dict[fav_thing])

fav_tree = 'tree'
print(fav_dict[fav_tree])

fav_dict.update(org = 'bacteria')
print(fav_dict)

for key in fav_dict:
  favs = fav_dict[key]
  print (key, favs)

myset = set('ATGTGGGGAT')
myset2 = {'ATGCCTAGCG'}

print(myset, myset2)

setA = {3, 14, 15, 9, 26, 5, 35, 9}
setB = {60, 22, 14, 0, 9}

difference = setA - setB
print('difference is', difference)
union = setA | setB
print('union is', union)
intersection = setA & setB
print('intersection is', intersection)
symdiff = setA ^ setB
print('symmetric difference is', symdiff)

seq ='GAACTCCAAAAATGAAAACATAGTAGCAATCAAAGCATCCCACTATTTTTTGTCTCTCGTTTCATTAGCGTTGTAAATTACTGATACCCTACTATACCTCTACAAGGCCTTTGTCATCTTTTTACTCAAGTGTGAAATCATCACTTATTGTATGAAGGATGAGCTTTCCGTTCGCTAGTTTGCTGAAAAGGCCTTCTGCAATAAGCTCTCTATTATCTTTAAAAAAACCTGGTTCCTGGTCTTCCATTCTGCTAAAAGCTGTAGGGGTTTTATCACGAGATTCCCGTTGGCATTCTGACTTATTAAAAATGCTTACAGAAGAAATGGATTCTTTAAATGGTCAAATTAATACGTGGACAGATAATAATCCTTTATTAGATGAAATTACGAAGCCATACAGAAAATCTTCAACTCGTTTTTTTCATCCGCTTCTTGTACTTCTAATGTCTAGAGCATCAGTAAATGGGGATCCACCGAGTCAGCAACTATTTCAAAGGTACAAACAACTTGCCCGTGTAACAGAATTGATTCATGCTGCCAATATAATTCATATTAATATTGGAGAAGAACAAAGCAACGAACAGATTAAACTTGCAACGTTGGTTGGAGATTATTTACTCGGAAAGGCGTCTGTTGATTTAGCACATTTAGAAAACAACGCTATTACAGAAATTATGGCTTCTGTTATTGCAAACTTAGTTGAAGGGCACTTCGGAAGCCGACAAAATGGCTCTGTTGGTTTGTCAAACGAACGAACCATCCTTCTGCAATCAGCCTTTATGCCAGCAAAGGCATGTTTATGCGCAAGCATATTGAATAACTCATCACAATACATTAATGATGCGTGTTTCAATTATGGAAAATTTCTAGGCTTATCGCTGCAACTGGCCCATAAGCCTGTATCTCCTGACGCCCAAGTTTTGCAAAAGAATAATGACATTTTGAAAACATATGTTGAGAATGCCAAGAGCTCATTGTCTGTTTTCCCCGATATAGAGGCTAAGCAAGCTCTCATGGAAATCGCTAATAGTGTTTCGAAGTAATCGACAGGTATTGTATCCTGGATTAATATTAGGGTGGCTCATGCATGCTCGTGCAATCGTAACAAATATGTCTTTCTTTTACGAATTTTAACGCTTCAATATAAATCATATTTTTCCTCA'
nt_dict = {}
for nt in seq:
   nt_dict[nt] = seq.count(nt)

print(nt_dict)

GC_content = (nt_dict['C'] + nt_dict['G']) / len(seq) *100
print ('GC content:' , GC_content)

for k, v in nt_dict.items():
	print(k, v)
